// All 20 blog posts as skeleton metadata (metadata + outline + excerpt only)
// Wave 1 (first 5) get enriched with full content via wave-1.ts
// Wave 2 + Wave 3 remain skeleton until UX Copywriter fills them in later waves

import type { RichBlogPost } from './types'

/**
 * Wave assignment per Content Marketing Manager decision (wave-1-final.md):
 * - Wave 1 (Apr 23 → May 7, 2026): 5 flagship posts, FULL content
 * - Wave 2 (May 11 → Jul 17, 2026): 8 posts, SKELETON initially
 * - Wave 3 (Jul 20 → Oct 30, 2026): 7 posts, SKELETON initially
 *
 * Status values:
 * - 'published' = full content shipped (Wave 1 after Copywriter fills)
 * - 'skeleton'  = metadata + outline shown only; UX is "Coming soon" style card
 * - 'scheduled' = full content written but not yet past publish date
 */

export const BLOG_SKELETONS: RichBlogPost[] = [
  // ─── WAVE 1 (5 flagship — filled by wave-1.ts) ───
  {
    slug: 'how-to-find-100-verified-suppliers-in-under-an-hour',
    status: 'skeleton',
    title: 'How to Find 100+ Verified Suppliers in Under an Hour (Without Hiring Anyone)',
    titlePl: 'Jak znaleźć 100+ zweryfikowanych dostawców w godzinę (bez zatrudniania nikogo)',
    excerpt: 'The 30-hour manual Excel baseline is dead. Here is the 4-step AI workflow that replaces it — without hiring, without enterprise software, and without losing sourcing quality.',
    excerptPl: '30-godzinny Excel baseline umarł. Oto 4-krokowy AI workflow który go zastępuje — bez zatrudniania, bez enterprise software, bez tracenia jakości sourcingu.',
    date: '2026-04-23',
    readTime: '8 min read',
    readTimePl: '8 min czytania',
    wordCount: 2200,
    pillar: 'ai-sourcing-automation',
    persona: 'P2',
    funnel: 'TOFU',
    category: 'AI Sourcing Automation',
    categoryPl: 'AI Sourcing',
    primaryKeyword: 'how to find suppliers',
    secondaryKeywords: ['supplier discovery tool', 'find verified suppliers', 'ai supplier search', 'automated supplier sourcing'],
    searchVolume: 1200,
    jsonLdType: 'HowTo',
    author: { name: 'Rafał Ignaczak', role: 'Founder, Procurea', avatarKey: 'rafal' },
    outline: 'Intro: 30h Excel vs 1h Procurea. Step 1: describe category. Step 2: AI search multi-lang. Step 3: screening & dedup. Step 4: export. Close: ROI calc + CTA.',
    relatedPosts: ['the-30-hour-problem', 'rfq-automation-workflows', 'european-nearshoring-guide-2026', 'sourcing-funnel-explained', 'rfq-comparison-template-buyers-use'],
    relatedFeatures: ['fAiSourcing', 'fCompanyRegistry'],
    relatedIndustries: ['iManufacturing', 'iRetail'],
    primaryCta: { text: 'Start free with 10 credits', textPl: 'Zacznij za darmo z 10 kredytami', href: 'https://app.procurea.io/signup', type: 'trial' },
    heroBackgroundKey: 'ai-sourcing',
  },
  {
    slug: 'the-30-hour-problem',
    status: 'skeleton',
    title: 'The 30-Hour Problem: Why Manual Sourcing Is Killing Your Margin',
    titlePl: 'Problem 30 godzin: dlaczego ręczny sourcing zabija twoją marżę',
    excerpt: 'Anatomy of a 30-hour sourcing campaign — cost breakdown, where time actually goes, and the ROI math that makes automation a no-brainer.',
    excerptPl: 'Anatomia 30-godzinnej kampanii sourcingowej — podział kosztów, gdzie naprawdę idzie czas, i matematyka ROI która robi automatyzację oczywistą.',
    date: '2026-04-27',
    readTime: '7 min read',
    readTimePl: '7 min czytania',
    wordCount: 1800,
    pillar: 'ai-sourcing-automation',
    persona: 'P2',
    funnel: 'TOFU',
    category: 'AI Sourcing Automation',
    categoryPl: 'AI Sourcing',
    primaryKeyword: 'procurement efficiency',
    secondaryKeywords: ['manual sourcing cost', 'procurement productivity', 'sourcing hours', 'procurement roi'],
    searchVolume: 600,
    jsonLdType: 'Article',
    author: { name: 'Rafał Ignaczak', role: 'Founder, Procurea', avatarKey: 'rafal' },
    outline: 'Anatomy of a 30h campaign. Cost breakdown (salary + opportunity). Where time actually goes. Automatable vs non-automatable. Before/after case. ROI math.',
    relatedPosts: ['how-to-find-100-verified-suppliers-in-under-an-hour', 'rfq-automation-workflows', 'sourcing-funnel-explained'],
    relatedFeatures: ['fAiSourcing', 'fEmailOutreach'],
    relatedIndustries: ['iManufacturing'],
    leadMagnetSlug: 'tco-calculator',
    primaryCta: { text: 'Book a 15-min walkthrough', textPl: 'Umów 15-min prezentację', href: 'https://cal.com/procurea/demo', type: 'demo' },
    heroBackgroundKey: 'ai-sourcing',
  },
  {
    slug: 'european-nearshoring-guide-2026',
    status: 'skeleton',
    title: "A Procurement Manager's Guide to European Nearshoring in 2026",
    titlePl: 'Przewodnik procurement managera po europejskim nearshoringu w 2026',
    excerpt: 'Post-COVID, tariffs, and CSRD are pushing production out of China. Here is the country-by-country playbook — Poland, Czech Republic, Turkey, Portugal, Romania, Hungary.',
    excerptPl: 'Post-COVID, cła i CSRD wypychają produkcję z Chin. Oto playbook kraj-po-kraju — Polska, Czechy, Turcja, Portugalia, Rumunia, Węgry.',
    date: '2026-04-30',
    readTime: '11 min read',
    readTimePl: '11 min czytania',
    wordCount: 2800,
    pillar: 'multilingual-outreach',
    persona: 'P1',
    funnel: 'TOFU',
    category: 'Multilingual Outreach',
    categoryPl: 'Sourcing Międzynarodowy',
    primaryKeyword: 'european nearshoring',
    secondaryKeywords: ['nearshore manufacturing europe', 'china plus one', 'supply chain diversification', 'nearshoring playbook'],
    searchVolume: 1800,
    jsonLdType: 'Article',
    author: { name: 'Procurea Research Team', role: 'Strategic Sourcing', avatarKey: 'research' },
    outline: 'Context: supply chain shocks 2020-25. Why Europe. Country-by-country (PL, CZ, TR, PT, RO, HU). Cost vs proximity tradeoffs. Certification landscape. Playbook for diversification.',
    relatedPosts: ['china-plus-one-strategy', 'turkey-vs-poland-vs-portugal-textiles', 'german-manufacturer-sourcing', 'tco-beat-lowest-price-trap'],
    relatedFeatures: ['fAiSourcing', 'fMultilingualOutreach'],
    relatedIndustries: ['iManufacturing', 'iRetail'],
    leadMagnetSlug: 'nearshore-migration-playbook',
    primaryCta: { text: 'Book strategy call', textPl: 'Umów rozmowę strategiczną', href: 'https://cal.com/procurea/strategy', type: 'calendar' },
    heroBackgroundKey: 'multilingual',
  },
  {
    slug: 'rfq-automation-workflows',
    status: 'skeleton',
    title: "RFQ Automation: What It Is, Why Excel Won't Cut It, and 5 Workflows That Work",
    titlePl: 'Automatyzacja RFQ: czym jest, dlaczego Excel nie wystarczy, i 5 workflow które działają',
    excerpt: 'Define RFQ automation. Problem with Excel-based RFQs. 5 workflows: bulk outreach, templated offers, scoring, follow-ups, comparison. Plus free template.',
    excerptPl: 'Definicja automatyzacji RFQ. Problem z Excel-based RFQ. 5 workflow: bulk outreach, szablonowe oferty, scoring, follow-upy, porównanie. Plus darmowy szablon.',
    date: '2026-05-04',
    readTime: '8 min read',
    readTimePl: '8 min czytania',
    wordCount: 2000,
    pillar: 'offer-comparison',
    persona: 'P2',
    funnel: 'TOFU',
    category: 'Offer Comparison',
    categoryPl: 'Porównanie Ofert',
    primaryKeyword: 'rfq automation',
    secondaryKeywords: ['automated rfq', 'rfq process automation', 'e-rfq', 'rfq workflow'],
    searchVolume: 700,
    jsonLdType: 'Article',
    author: { name: 'Rafał Ignaczak', role: 'Founder, Procurea', avatarKey: 'rafal' },
    outline: 'Define RFQ automation. Problem with Excel-based RFQs. 5 workflows: bulk outreach, templated offers, scoring, follow-ups, comparison. Tool landscape (brief). Close with template download.',
    relatedPosts: ['how-to-find-100-verified-suppliers-in-under-an-hour', 'vendor-scoring-10-criteria', 'rfq-comparison-template-buyers-use'],
    relatedFeatures: ['fEmailOutreach', 'fSupplierPortal', 'fOfferComparison'],
    relatedIndustries: ['iManufacturing', 'iEvents'],
    leadMagnetSlug: 'rfq-comparison-template',
    primaryCta: { text: 'Download free RFQ template', textPl: 'Pobierz darmowy szablon RFQ', href: '/resources/library/rfq-comparison-template', type: 'magnet' },
    heroBackgroundKey: 'offer-comparison',
  },
  {
    slug: 'turkey-vs-poland-vs-portugal-textiles',
    status: 'skeleton',
    title: 'Turkey vs Poland vs Portugal: Where to Source Textiles in 2026',
    titlePl: 'Turcja vs Polska vs Portugalia: gdzie szukać tekstyliów w 2026',
    excerpt: 'Category-specific deep-dive for textile sourcing. Country-by-country: capacity, MOQ, certs (GOTS, OEKO-TEX), lead time, price ranges. Decision matrix included.',
    excerptPl: 'Dogłębna analiza sourcingu tekstyliów. Kraj-po-kraju: moce, MOQ, certyfikaty, lead time, ceny. Decision matrix.',
    date: '2026-05-07',
    readTime: '8 min read',
    readTimePl: '8 min czytania',
    wordCount: 2000,
    pillar: 'multilingual-outreach',
    persona: 'P2',
    funnel: 'TOFU',
    category: 'Multilingual Outreach',
    categoryPl: 'Sourcing Międzynarodowy',
    primaryKeyword: 'textile sourcing europe',
    secondaryKeywords: ['turkey textile manufacturers', 'polish textile suppliers', 'portugal textile', 'european textile sourcing'],
    searchVolume: 400,
    jsonLdType: 'Article',
    author: { name: 'Procurea Research Team', role: 'Strategic Sourcing', avatarKey: 'research' },
    outline: 'Country-by-country: capacity, MOQ, certs, lead time, price ranges. Decision matrix. Language & cultural notes. Where to verify. Ethical & GOTS/OEKO-TEX landscape.',
    relatedPosts: ['european-nearshoring-guide-2026', 'china-plus-one-strategy', 'german-manufacturer-sourcing'],
    relatedFeatures: ['fAiSourcing', 'fMultilingualOutreach'],
    relatedIndustries: ['iRetail', 'iManufacturing'],
    primaryCta: { text: 'Find textile suppliers', textPl: 'Znajdź dostawców tekstyliów', href: 'https://app.procurea.io/signup?category=textile', type: 'trial' },
    heroBackgroundKey: 'multilingual',
  },

  // ─── WAVE 2 (8 posts — skeleton until Copywriter writes) ───
  {
    slug: 'vat-vies-verification-3-minute-check',
    status: 'skeleton',
    title: 'VAT VIES Verification: The 3-Minute Check That Saves You €50k',
    titlePl: 'Weryfikacja VAT VIES: 3-minutowa kontrola która oszczędza €50k',
    excerpt: 'Why VAT verification matters for cross-border procurement, how VIES works, when it gets wrong answers, and how to automate verification at scale.',
    excerptPl: 'Dlaczego weryfikacja VAT ma znaczenie przy sourcingu cross-border, jak działa VIES, kiedy się myli, i jak zautomatyzować weryfikację na skalę.',
    date: '2026-05-11',
    readTime: '6 min read',
    readTimePl: '6 min czytania',
    wordCount: 1500,
    pillar: 'supplier-intelligence',
    persona: 'P1',
    funnel: 'TOFU',
    category: 'Supplier Intelligence',
    categoryPl: 'Weryfikacja Dostawców',
    primaryKeyword: 'vat vies check',
    secondaryKeywords: ['vies verification', 'eu vat check', 'cross-border vat', 'supplier verification'],
    searchVolume: 800,
    jsonLdType: 'HowTo',
    author: { name: 'Procurea Research Team', role: 'Compliance', avatarKey: 'research' },
    outline: 'Why VAT verification matters (cross-border VAT reverse charge, audit). How VIES works. Manual flow (3 steps). When VIES is wrong. Automated verification at scale. Real cost story (€50k lost invoice).',
    relatedPosts: ['supplier-certifications-guide', 'supplier-risk-management-2026', 'supplier-database-stale-40-percent'],
    relatedFeatures: ['fCompanyRegistry', 'fEnrichment'],
    relatedIndustries: ['iManufacturing'],
    primaryCta: { text: 'Verify a supplier free', textPl: 'Zweryfikuj dostawcę za darmo', href: 'https://app.procurea.io/signup', type: 'trial' },
    heroBackgroundKey: 'supplier-intel',
  },
  {
    slug: 'ai-procurement-software-7-features-2026',
    status: 'skeleton',
    title: 'AI Procurement Software: 7 Features Worth Paying For in 2026',
    titlePl: 'Oprogramowanie AI do procurement: 7 funkcji wartych zapłaty w 2026',
    excerpt: 'The 2026 AI procurement landscape — 7 must-have features, what is hype vs real, and a vendor shortlist framework. Honest teardown.',
    excerptPl: 'Krajobraz AI procurement w 2026 — 7 must-have funkcji, co jest hypem a co prawdą, framework wyboru vendorów. Uczciwy teardown.',
    date: '2026-05-18',
    readTime: '8 min read',
    readTimePl: '8 min czytania',
    wordCount: 2200,
    pillar: 'ai-sourcing-automation',
    persona: 'Mixed',
    funnel: 'MOFU',
    category: 'AI Sourcing Automation',
    categoryPl: 'AI Sourcing',
    primaryKeyword: 'ai procurement software',
    secondaryKeywords: ['ai procurement platform', 'procurement tools comparison', 'best procurement software', 'ai sourcing vendors'],
    searchVolume: 900,
    jsonLdType: 'Article',
    author: { name: 'Rafał Ignaczak', role: 'Founder, Procurea', avatarKey: 'rafal' },
    outline: '2026 AI landscape. 7 must-have features (multi-lang search, verification, email automation, offer structuring, scoring, ERP sync, audit trail). What\'s hype vs real. Vendor shortlist framework.',
    relatedPosts: ['buyers-guide-12-questions-ai-sourcing', 'how-to-find-100-verified-suppliers-in-under-an-hour', 'rfq-automation-workflows', 'the-30-hour-problem', 'sap-ariba-alternative-procurement'],
    relatedFeatures: ['fAiSourcing', 'fMultilingualOutreach', 'fOfferComparison'],
    relatedIndustries: ['iManufacturing', 'iRetail'],
    primaryCta: { text: 'Compare Procurea vs alternatives', textPl: 'Porównaj Procurea z alternatywami', href: '/vs-manual-sourcing', type: 'demo' },
    heroBackgroundKey: 'ai-sourcing',
  },
  {
    slug: 'supplier-risk-management-2026',
    status: 'skeleton',
    title: 'Supplier Risk Management: A 2026 Checklist for Procurement Teams',
    titlePl: 'Zarządzanie ryzykiem dostawców: checklista 2026 dla zespołów procurement',
    excerpt: 'Risk categories: financial, ops, geopolitical, ESG, cyber. 2026-specific risks (CSDDD, tariffs, CSRD). 20-point checklist + how to operationalize monitoring.',
    excerptPl: 'Kategorie ryzyka: finansowe, operacyjne, geopolityczne, ESG, cyber. Ryzyka specyficzne dla 2026. 20-punktowa checklista.',
    date: '2026-05-25',
    readTime: '10 min read',
    readTimePl: '10 min czytania',
    wordCount: 2500,
    pillar: 'supplier-intelligence',
    persona: 'P1',
    funnel: 'MOFU',
    category: 'Supplier Intelligence',
    categoryPl: 'Weryfikacja Dostawców',
    primaryKeyword: 'supplier risk management',
    secondaryKeywords: ['vendor risk assessment', 'supplier due diligence', 'third party risk', 'csddd compliance'],
    searchVolume: 1500,
    jsonLdType: 'Article',
    author: { name: 'Procurea Research Team', role: 'Compliance', avatarKey: 'research' },
    outline: 'Risk categories: financial, ops, geopolitical, ESG, cyber. 2026-specific risks. Checklist: 20 checks. Tools landscape. How to operationalize monitoring. Case: one missed flag, 3-month delay.',
    relatedPosts: ['vat-vies-verification-3-minute-check', 'supplier-certifications-guide', 'supplier-database-stale-40-percent', 'buyers-guide-12-questions-ai-sourcing', 'tco-beat-lowest-price-trap'],
    relatedFeatures: ['fCompanyRegistry', 'fEnrichment'],
    relatedIndustries: ['iManufacturing', 'iHealthcare'],
    leadMagnetSlug: 'supplier-risk-checklist-2026',
    primaryCta: { text: 'Book risk audit call', textPl: 'Umów audyt ryzyka', href: 'https://cal.com/procurea/risk', type: 'calendar' },
    heroBackgroundKey: 'supplier-intel',
  },
  {
    slug: 'german-manufacturer-sourcing',
    status: 'skeleton',
    title: 'How to Source from German Manufacturers Without Speaking German',
    titlePl: 'Jak pozyskiwać od niemieckich producentów bez znajomości niemieckiego',
    excerpt: 'Why German suppliers are worth the effort (quality, IATF), where to find them (Wer-liefert-was, Handelsregister), language barriers, Mittelstand culture, email templates.',
    excerptPl: 'Dlaczego niemieccy dostawcy są warci wysiłku, gdzie ich szukać, bariery językowe, kultura Mittelstand, szablony emaili.',
    date: '2026-06-01',
    readTime: '7 min read',
    readTimePl: '7 min czytania',
    wordCount: 1700,
    pillar: 'multilingual-outreach',
    persona: 'P2',
    funnel: 'TOFU',
    category: 'Multilingual Outreach',
    categoryPl: 'Sourcing Międzynarodowy',
    primaryKeyword: 'german manufacturer sourcing',
    secondaryKeywords: ['how to find german suppliers', 'wer liefert was', 'mittelstand suppliers', 'sourcing from germany'],
    searchVolume: 500,
    jsonLdType: 'HowTo',
    author: { name: 'Procurea Research Team', role: 'Strategic Sourcing', avatarKey: 'research' },
    outline: 'Why German suppliers worth effort (quality, IATF). Where to find them (Wer-liefert-was, Handelsregister, category portals). Language: when it matters, when not. Certs & Mittelstand culture. Real email template (DE/EN).',
    relatedPosts: ['european-nearshoring-guide-2026', 'turkey-vs-poland-vs-portugal-textiles', 'supplier-certifications-guide'],
    relatedFeatures: ['fAiSourcing', 'fMultilingualOutreach'],
    relatedIndustries: ['iManufacturing'],
    primaryCta: { text: 'Try multi-language search', textPl: 'Wypróbuj wyszukiwanie wielojęzyczne', href: 'https://app.procurea.io/signup', type: 'trial' },
    heroBackgroundKey: 'multilingual',
  },
  {
    slug: 'rfq-comparison-template-buyers-use',
    status: 'skeleton',
    title: 'The Free RFQ Comparison Template Buyers Actually Use [Excel + Notion]',
    titlePl: 'Darmowy szablon porównania RFQ którego kupcy naprawdę używają',
    excerpt: '10 comparison criteria, tiered pricing fields, MOQ / lead time / Incoterms, scoring formula. Limits of Excel + when to upgrade.',
    excerptPl: '10 kryteriów porównawczych, pola pricing tiered, MOQ / lead time / Incoterms, formuła scoringu. Ograniczenia Excel + kiedy go porzucić.',
    date: '2026-06-08',
    readTime: '6 min read',
    readTimePl: '6 min czytania',
    wordCount: 1600,
    pillar: 'offer-comparison',
    persona: 'P2',
    funnel: 'TOFU',
    category: 'Offer Comparison',
    categoryPl: 'Porównanie Ofert',
    primaryKeyword: 'rfq comparison template',
    secondaryKeywords: ['rfq template excel', 'supplier offer template', 'quote comparison', 'rfq scoring template'],
    searchVolume: 900,
    jsonLdType: 'Article',
    author: { name: 'Rafał Ignaczak', role: 'Founder, Procurea', avatarKey: 'rafal' },
    outline: 'Template download as gated asset. 10 comparison criteria. Tiered pricing fields. MOQ / lead time / Incoterms. Scoring formula. Exclusive field list: payment terms, certs, warranty. Limits of Excel + when to upgrade.',
    relatedPosts: ['rfq-automation-workflows', 'vendor-scoring-10-criteria', 'tco-beat-lowest-price-trap'],
    relatedFeatures: ['fOfferComparison', 'fOfferCollection'],
    relatedIndustries: ['iManufacturing', 'iEvents'],
    leadMagnetSlug: 'rfq-comparison-template',
    primaryCta: { text: 'Download template', textPl: 'Pobierz szablon', href: '/resources/library/rfq-comparison-template', type: 'magnet' },
    heroBackgroundKey: 'offer-comparison',
  },
  {
    slug: 'china-plus-one-strategy',
    status: 'skeleton',
    title: 'China+1 Strategy: A Practical Playbook for 2026 Diversification',
    titlePl: 'Strategia China+1: praktyczny playbook dywersyfikacji na 2026',
    excerpt: 'Context: 2025 tariff shocks. What China+1 means (not China-out). Alt countries by category. Sequencing (pilot, parallel, ramp). Board-ready template.',
    excerptPl: 'Kontekst: szoki celne 2025. Co to China+1 (nie China-out). Alt kraje per kategoria. Sekwencjonowanie. Szablon gotowy na zarząd.',
    date: '2026-06-15',
    readTime: '10 min read',
    readTimePl: '10 min czytania',
    wordCount: 2400,
    pillar: 'multilingual-outreach',
    persona: 'P1',
    funnel: 'MOFU',
    category: 'Multilingual Outreach',
    categoryPl: 'Sourcing Międzynarodowy',
    primaryKeyword: 'china+1 sourcing',
    secondaryKeywords: ['china plus one', 'supply chain diversification', 'move production from china', 'alternative to china'],
    searchVolume: 600,
    jsonLdType: 'Article',
    author: { name: 'Procurea Research Team', role: 'Strategic Sourcing', avatarKey: 'research' },
    outline: 'Context: 2025 tariff shocks. What China+1 means (not China-out). Alt countries by category. Sequencing (pilot, parallel, ramp). Cost realities. Board-ready template.',
    relatedPosts: ['european-nearshoring-guide-2026', 'turkey-vs-poland-vs-portugal-textiles', 'tco-beat-lowest-price-trap'],
    relatedFeatures: ['fAiSourcing', 'fMultilingualOutreach'],
    relatedIndustries: ['iManufacturing', 'iRetail'],
    leadMagnetSlug: 'nearshore-migration-playbook',
    primaryCta: { text: 'Build a diversification plan', textPl: 'Zbuduj plan dywersyfikacji', href: 'https://cal.com/procurea/strategy', type: 'calendar' },
    heroBackgroundKey: 'multilingual',
  },
  {
    slug: 'vendor-scoring-10-criteria',
    status: 'skeleton',
    title: 'Vendor Scoring: A 10-Criteria Framework for Fair Supplier Evaluation',
    titlePl: 'Scoring dostawców: framework 10 kryteriów dla uczciwej ewaluacji',
    excerpt: 'Why ad-hoc scoring fails audit. 10 criteria (price, quality, lead time, MOQ, payment, certs, capacity, financial, ESG, responsiveness). Weighting logic + template.',
    excerptPl: 'Dlaczego ad-hoc scoring nie przechodzi audytu. 10 kryteriów + logika ważenia + szablon.',
    date: '2026-06-22',
    readTime: '7 min read',
    readTimePl: '7 min czytania',
    wordCount: 1800,
    pillar: 'offer-comparison',
    persona: 'P2',
    funnel: 'TOFU',
    category: 'Offer Comparison',
    categoryPl: 'Porównanie Ofert',
    primaryKeyword: 'vendor scoring framework',
    secondaryKeywords: ['supplier scorecard', 'vendor evaluation criteria', 'supplier rating', 'vendor rating template'],
    searchVolume: 400,
    jsonLdType: 'Article',
    author: { name: 'Rafał Ignaczak', role: 'Founder, Procurea', avatarKey: 'rafal' },
    outline: 'Why ad-hoc scoring fails audit. 10 criteria (price, quality, lead time, MOQ, payment, certs, capacity, financial, ESG, responsiveness). Weighting logic. Template. Defensibility for procurement audit.',
    relatedPosts: ['rfq-automation-workflows', 'rfq-comparison-template-buyers-use', 'supplier-certifications-guide'],
    relatedFeatures: ['fOfferComparison', 'fOfferCollection'],
    relatedIndustries: ['iManufacturing'],
    leadMagnetSlug: 'vendor-scoring-framework',
    primaryCta: { text: 'Download scoring template', textPl: 'Pobierz szablon scoringu', href: '/resources/library/vendor-scoring-framework', type: 'magnet' },
    heroBackgroundKey: 'offer-comparison',
  },
  {
    slug: 'supplier-certifications-guide',
    status: 'skeleton',
    title: 'ISO 9001 vs IATF 16949 vs FDA: Supplier Certifications That Actually Matter',
    titlePl: 'ISO 9001 vs IATF 16949 vs FDA: certyfikaty dostawców które naprawdę mają znaczenie',
    excerpt: 'Certification landscape: when each matters (industry-specific), how to verify (public registries vs self-attest), expiration tracking, red flags (fake certs, lapsed).',
    excerptPl: 'Krajobraz certyfikacji: kiedy każdy ma znaczenie, jak weryfikować, śledzenie wygaśnięć, red flagi.',
    date: '2026-07-06',
    readTime: '8 min read',
    readTimePl: '8 min czytania',
    wordCount: 2200,
    pillar: 'supplier-intelligence',
    persona: 'P1',
    funnel: 'MOFU',
    category: 'Supplier Intelligence',
    categoryPl: 'Weryfikacja Dostawców',
    primaryKeyword: 'supplier certifications guide',
    secondaryKeywords: ['iso 9001 supplier', 'iatf 16949', 'fda supplier compliance', 'supplier certification verification'],
    searchVolume: 300,
    jsonLdType: 'Article',
    author: { name: 'Procurea Research Team', role: 'Compliance', avatarKey: 'research' },
    outline: 'Certification landscape. When each matters (industry-specific). How to verify (public registries vs self-attest). Expiration tracking. Red flags (fake certs, lapsed).',
    relatedPosts: ['supplier-risk-management-2026', 'vat-vies-verification-3-minute-check', 'supplier-database-stale-40-percent', 'sap-ariba-alternative-procurement'],
    relatedFeatures: ['fCompanyRegistry', 'fEnrichment'],
    relatedIndustries: ['iManufacturing', 'iHealthcare'],
    primaryCta: { text: 'Verify certifications free', textPl: 'Zweryfikuj certyfikaty za darmo', href: 'https://app.procurea.io/signup', type: 'trial' },
    heroBackgroundKey: 'supplier-intel',
  },

  // ─── WAVE 3 (7 posts — skeleton, BOFU + long-tail) ───
  {
    slug: 'supplier-database-stale-40-percent',
    status: 'skeleton',
    title: 'Why 40% of Your Supplier Database Goes Stale Every Year (And What to Do)',
    titlePl: 'Dlaczego 40% twojej bazy dostawców starzeje się co rok (i co z tym zrobić)',
    excerpt: 'The 40% stat — why data decays (contacts, certs, capacity), impact (failed RFQs, fines), fix (continuous refresh vs annual audit), + self-audit template.',
    excerptPl: 'Statystyka 40% — dlaczego dane starzeją się, konsekwencje, jak to naprawić.',
    date: '2026-07-20',
    readTime: '6 min read',
    readTimePl: '6 min czytania',
    wordCount: 1600,
    pillar: 'supplier-intelligence',
    persona: 'P2',
    funnel: 'TOFU',
    category: 'Supplier Intelligence',
    categoryPl: 'Weryfikacja Dostawców',
    primaryKeyword: 'supplier master data quality',
    secondaryKeywords: ['supplier data refresh', 'stale supplier database', 'vendor master data', 'mdm procurement'],
    searchVolume: 250,
    jsonLdType: 'Article',
    author: { name: 'Procurea Research Team', role: 'Data', avatarKey: 'research' },
    outline: 'The 40% stat (source). Why data decays: contacts, certs, capacity. Impact: failed RFQs, compliance fines. Fix: continuous refresh vs annual audit. Procurea\'s approach. Template: quick self-audit.',
    relatedPosts: ['supplier-certifications-guide', 'supplier-risk-management-2026', 'vat-vies-verification-3-minute-check'],
    relatedFeatures: ['fCompanyRegistry', 'fEnrichment'],
    relatedIndustries: ['iManufacturing'],
    primaryCta: { text: 'Audit your supplier database', textPl: 'Przeprowadź audyt bazy', href: 'https://app.procurea.io/signup', type: 'trial' },
    heroBackgroundKey: 'supplier-intel',
  },
  {
    slug: 'netsuite-supplier-management',
    status: 'skeleton',
    title: 'Oracle NetSuite Supplier Management: What Procurement Teams Actually Need',
    titlePl: 'Oracle NetSuite zarządzanie dostawcami: co zespoły procurement naprawdę potrzebują',
    excerpt: 'NetSuite vendor record capabilities + gaps (sourcing, outreach, verification). Third-party tools vs native. Procurea + NetSuite specifics.',
    excerptPl: 'Możliwości NetSuite vendor record + luki. Narzędzia third-party vs native. Specyfika Procurea + NetSuite.',
    date: '2026-08-03',
    readTime: '7 min read',
    readTimePl: '7 min czytania',
    wordCount: 1800,
    pillar: 'erp-crm-integration',
    persona: 'P1',
    funnel: 'BOFU',
    category: 'ERP/CRM Integration',
    categoryPl: 'Integracje ERP',
    primaryKeyword: 'netsuite supplier management',
    secondaryKeywords: ['netsuite sourcing tool', 'netsuite procurement', 'netsuite vendor', 'erp supplier management'],
    searchVolume: 250,
    jsonLdType: 'Article',
    author: { name: 'Procurea Research Team', role: 'Integrations', avatarKey: 'research' },
    outline: 'NetSuite vendor record capabilities. Gaps (sourcing, outreach, verification). Third-party tools vs native. Procurea + NetSuite specifics. SuiteBundle vs API. Field mapping notes.',
    relatedPosts: ['sap-ariba-alternative-procurement', 'salesforce-for-procurement', 'ai-procurement-software-7-features-2026'],
    relatedFeatures: ['fAiSourcing', 'fCompanyRegistry'],
    relatedIndustries: ['iManufacturing'],
    primaryCta: { text: 'Book NetSuite integration call', textPl: 'Umów rozmowę o integracji NetSuite', href: 'https://cal.com/procurea/netsuite', type: 'calendar' },
    heroBackgroundKey: 'erp-integration',
  },
  {
    slug: 'sap-ariba-alternative-procurement',
    status: 'skeleton',
    title: 'SAP Ariba Alternative: How Mid-Market Teams Get Enterprise Sourcing Without the SAP Bill',
    titlePl: 'Alternatywa dla SAP Ariba: jak zespoły mid-market dostają enterprise sourcing bez rachunku SAP',
    excerpt: 'SAP Ariba cost + complexity reality. What mid-market procurement actually needs. How Procurea delivers 80% of Ariba value at 10% of cost + S/4HANA sync path (pilot status).',
    excerptPl: 'Koszty i złożoność SAP Ariba. Co naprawdę potrzebuje mid-market procurement. Jak Procurea dostarcza 80% wartości Ariba za 10% kosztów.',
    date: '2026-08-10',
    readTime: '8 min read',
    readTimePl: '8 min czytania',
    wordCount: 1800,
    pillar: 'erp-crm-integration',
    persona: 'P1',
    funnel: 'BOFU',
    category: 'ERP/CRM Integration',
    categoryPl: 'Integracje ERP',
    primaryKeyword: 'sap ariba alternative',
    secondaryKeywords: ['ariba replacement', 'sap s/4hana supplier sync', 'mid-market procurement', 'affordable sourcing platform'],
    searchVolume: 590,
    jsonLdType: 'Article',
    author: { name: 'Procurea Research Team', role: 'Integrations', avatarKey: 'research' },
    outline: 'SAP Ariba cost + complexity pain. Mid-market needs vs what Ariba sells. Procurea as sourcing layer over existing SAP. S/4HANA sync (pilot). When you outgrow Procurea (scale + go Ariba).',
    relatedPosts: ['netsuite-supplier-management', 'salesforce-for-procurement', 'ai-procurement-software-7-features-2026'],
    relatedFeatures: ['fAiSourcing', 'fOfferComparison'],
    relatedIndustries: ['iManufacturing'],
    primaryCta: { text: 'Book SAP integration call', textPl: 'Umów rozmowę o integracji SAP', href: 'https://cal.com/procurea/sap', type: 'calendar' },
    heroBackgroundKey: 'erp-integration',
  },
  {
    slug: 'tco-beat-lowest-price-trap',
    status: 'skeleton',
    title: 'Total Cost of Ownership (TCO): How to Beat the Lowest-Price Trap in Sourcing',
    titlePl: 'Total Cost of Ownership: jak pokonać pułapkę najniższej ceny w sourcingu',
    excerpt: 'Why lowest unit price ≠ best value. TCO components (price, logistics, duties, quality cost, payment, switching). Worked example + calculator.',
    excerptPl: 'Dlaczego najniższa cena ≠ najlepsza wartość. Komponenty TCO. Przykład + kalkulator.',
    date: '2026-08-17',
    readTime: '8 min read',
    readTimePl: '8 min czytania',
    wordCount: 2000,
    pillar: 'offer-comparison',
    persona: 'Mixed',
    funnel: 'MOFU',
    category: 'Offer Comparison',
    categoryPl: 'Porównanie Ofert',
    primaryKeyword: 'tco procurement',
    secondaryKeywords: ['total cost of ownership', 'landed cost', 'true cost supplier', 'tco calculator'],
    searchVolume: 600,
    jsonLdType: 'Article',
    author: { name: 'Procurea Research Team', role: 'Analytics', avatarKey: 'research' },
    outline: 'Why lowest unit price ≠ best value. TCO components (price, logistics, duties, quality cost, payment terms, switching cost). Worked example. TCO calculator (gated asset).',
    relatedPosts: ['vendor-scoring-10-criteria', 'china-plus-one-strategy', 'rfq-automation-workflows'],
    relatedFeatures: ['fOfferComparison', 'fOfferCollection'],
    relatedIndustries: ['iManufacturing', 'iRetail'],
    leadMagnetSlug: 'tco-calculator',
    primaryCta: { text: 'Download TCO calculator', textPl: 'Pobierz kalkulator TCO', href: '/resources/library/tco-calculator', type: 'magnet' },
    heroBackgroundKey: 'offer-comparison',
  },
  {
    slug: 'sourcing-funnel-explained',
    status: 'skeleton',
    title: 'From 500 Google Results to 120 Verified Suppliers: The Sourcing Funnel Explained',
    titlePl: 'Od 500 wyników Google do 120 zweryfikowanych dostawców: lejek sourcingowy',
    excerpt: 'The funnel: queries → URLs → screened → verified → contacted. Conversion rates at each stage. Where most buyers fail (verification). Automation at each stage.',
    excerptPl: 'Lejek: zapytania → URL-e → screened → verified → kontakt. Wskaźniki konwersji. Gdzie większość kupców pada.',
    date: '2026-09-07',
    readTime: '7 min read',
    readTimePl: '7 min czytania',
    wordCount: 1700,
    pillar: 'ai-sourcing-automation',
    persona: 'P2',
    funnel: 'TOFU',
    category: 'AI Sourcing Automation',
    categoryPl: 'AI Sourcing',
    primaryKeyword: 'supplier discovery process',
    secondaryKeywords: ['sourcing funnel', 'supplier search conversion', 'ai supplier discovery', 'supplier qualification funnel'],
    searchVolume: 400,
    jsonLdType: 'Article',
    author: { name: 'Rafał Ignaczak', role: 'Founder, Procurea', avatarKey: 'rafal' },
    outline: 'The funnel: queries → URLs → screened → verified → contacted. Conversion rates at each stage. Where most buyers fail (verification). Automation at each stage.',
    relatedPosts: ['how-to-find-100-verified-suppliers-in-under-an-hour', 'the-30-hour-problem', 'rfq-automation-workflows'],
    relatedFeatures: ['fAiSourcing', 'fCompanyRegistry'],
    relatedIndustries: ['iManufacturing', 'iRetail'],
    primaryCta: { text: 'See the funnel live', textPl: 'Zobacz lejek na żywo', href: 'https://app.procurea.io/signup', type: 'trial' },
    heroBackgroundKey: 'ai-sourcing',
  },
  {
    slug: 'salesforce-for-procurement',
    status: 'skeleton',
    title: 'Salesforce for Procurement: When It Works (And When You Need Something Else)',
    titlePl: 'Salesforce dla procurement: kiedy działa (i kiedy potrzebujesz czegoś innego)',
    excerpt: 'Why some teams run procurement in Salesforce. When it works (smaller teams, services). When it breaks (manufacturing, complex PO). Procurea + Salesforce sync patterns.',
    excerptPl: 'Dlaczego niektóre zespoły prowadzą procurement w Salesforce. Kiedy działa vs kiedy się łamie.',
    date: '2026-09-21',
    readTime: '6 min read',
    readTimePl: '6 min czytania',
    wordCount: 1500,
    pillar: 'erp-crm-integration',
    persona: 'P1',
    funnel: 'MOFU',
    category: 'ERP/CRM Integration',
    categoryPl: 'Integracje ERP',
    primaryKeyword: 'salesforce for procurement',
    secondaryKeywords: ['salesforce procurement integration', 'crm procurement', 'account-as-supplier', 'salesforce vendor management'],
    searchVolume: 320,
    jsonLdType: 'Article',
    author: { name: 'Procurea Research Team', role: 'Integrations', avatarKey: 'research' },
    outline: 'Why some teams run procurement in Salesforce (Account-as-Supplier). When it works (smaller teams, services-heavy). When it breaks (manufacturing, complex PO). Procurea + Salesforce sync patterns.',
    relatedPosts: ['sap-ariba-alternative-procurement', 'netsuite-supplier-management', 'ai-procurement-software-7-features-2026'],
    relatedFeatures: ['fAiSourcing', 'fCompanyRegistry'],
    relatedIndustries: ['iManufacturing', 'iRetail'],
    primaryCta: { text: 'Book Salesforce integration call', textPl: 'Umów rozmowę o integracji Salesforce', href: 'https://cal.com/procurea/salesforce', type: 'calendar' },
    heroBackgroundKey: 'erp-integration',
  },
  {
    slug: 'buyers-guide-12-questions-ai-sourcing',
    status: 'skeleton',
    title: "Buyer's Guide: 12 Questions to Ask Before Picking an AI Sourcing Tool",
    titlePl: 'Przewodnik kupującego: 12 pytań zanim wybierzesz narzędzie AI sourcing',
    excerpt: '12-question framework across search, verification, outreach, comparison, integration, security. How vendors dodge each question. Scorecard template.',
    excerptPl: '12-pytań framework. Jak vendorzy uciekają przed każdym pytaniem. Szablon scoringu.',
    date: '2026-10-05',
    readTime: '8 min read',
    readTimePl: '8 min czytania',
    wordCount: 2000,
    pillar: 'ai-sourcing-automation',
    persona: 'P1',
    funnel: 'MOFU',
    category: 'AI Sourcing Automation',
    categoryPl: 'AI Sourcing',
    primaryKeyword: 'ai sourcing tool comparison',
    secondaryKeywords: ['choose ai procurement software', 'ai sourcing evaluation', 'vendor selection procurement', 'rfp ai sourcing'],
    searchVolume: 300,
    jsonLdType: 'Article',
    author: { name: 'Rafał Ignaczak', role: 'Founder, Procurea', avatarKey: 'rafal' },
    outline: '12-question framework. Categories: search, verification, outreach, comparison, integration, security. How vendors dodge each question. Scorecard template.',
    relatedPosts: ['ai-procurement-software-7-features-2026', 'how-to-find-100-verified-suppliers-in-under-an-hour', 'supplier-risk-management-2026'],
    relatedFeatures: ['fAiSourcing', 'fOfferComparison'],
    relatedIndustries: ['iManufacturing'],
    primaryCta: { text: 'See how Procurea answers all 12', textPl: 'Zobacz jak Procurea odpowiada na 12', href: 'https://cal.com/procurea/demo', type: 'demo' },
    heroBackgroundKey: 'ai-sourcing',
  },
]
