import { isEN } from '@/i18n';

export interface CountryOption {
  code: string;
  name: string;
  flag: string;
  group: string;
}

export const COUNTRIES_PL: CountryOption[] = [
  // Europa
  { code: 'PL', name: 'Polska', flag: '\u{1F1F5}\u{1F1F1}', group: 'Europa' },
  { code: 'DE', name: 'Niemcy', flag: '\u{1F1E9}\u{1F1EA}', group: 'Europa' },
  { code: 'CZ', name: 'Czechy', flag: '\u{1F1E8}\u{1F1FF}', group: 'Europa' },
  { code: 'SK', name: 'Słowacja', flag: '\u{1F1F8}\u{1F1F0}', group: 'Europa' },
  { code: 'AT', name: 'Austria', flag: '\u{1F1E6}\u{1F1F9}', group: 'Europa' },
  { code: 'FR', name: 'Francja', flag: '\u{1F1EB}\u{1F1F7}', group: 'Europa' },
  { code: 'IT', name: 'Włochy', flag: '\u{1F1EE}\u{1F1F9}', group: 'Europa' },
  { code: 'ES', name: 'Hiszpania', flag: '\u{1F1EA}\u{1F1F8}', group: 'Europa' },
  { code: 'PT', name: 'Portugalia', flag: '\u{1F1F5}\u{1F1F9}', group: 'Europa' },
  { code: 'NL', name: 'Holandia', flag: '\u{1F1F3}\u{1F1F1}', group: 'Europa' },
  { code: 'BE', name: 'Belgia', flag: '\u{1F1E7}\u{1F1EA}', group: 'Europa' },
  { code: 'CH', name: 'Szwajcaria', flag: '\u{1F1E8}\u{1F1ED}', group: 'Europa' },
  { code: 'SE', name: 'Szwecja', flag: '\u{1F1F8}\u{1F1EA}', group: 'Europa' },
  { code: 'DK', name: 'Dania', flag: '\u{1F1E9}\u{1F1F0}', group: 'Europa' },
  { code: 'NO', name: 'Norwegia', flag: '\u{1F1F3}\u{1F1F4}', group: 'Europa' },
  { code: 'FI', name: 'Finlandia', flag: '\u{1F1EB}\u{1F1EE}', group: 'Europa' },
  { code: 'HU', name: 'Węgry', flag: '\u{1F1ED}\u{1F1FA}', group: 'Europa' },
  { code: 'RO', name: 'Rumunia', flag: '\u{1F1F7}\u{1F1F4}', group: 'Europa' },
  { code: 'BG', name: 'Bułgaria', flag: '\u{1F1E7}\u{1F1EC}', group: 'Europa' },
  { code: 'HR', name: 'Chorwacja', flag: '\u{1F1ED}\u{1F1F7}', group: 'Europa' },
  { code: 'SI', name: 'Słowenia', flag: '\u{1F1F8}\u{1F1EE}', group: 'Europa' },
  { code: 'LT', name: 'Litwa', flag: '\u{1F1F1}\u{1F1F9}', group: 'Europa' },
  { code: 'LV', name: 'Łotwa', flag: '\u{1F1F1}\u{1F1FB}', group: 'Europa' },
  { code: 'EE', name: 'Estonia', flag: '\u{1F1EA}\u{1F1EA}', group: 'Europa' },
  { code: 'IE', name: 'Irlandia', flag: '\u{1F1EE}\u{1F1EA}', group: 'Europa' },
  { code: 'GB', name: 'Wielka Brytania', flag: '\u{1F1EC}\u{1F1E7}', group: 'Europa' },
  { code: 'GR', name: 'Grecja', flag: '\u{1F1EC}\u{1F1F7}', group: 'Europa' },
  { code: 'UA', name: 'Ukraina', flag: '\u{1F1FA}\u{1F1E6}', group: 'Europa' },
  { code: 'RS', name: 'Serbia', flag: '\u{1F1F7}\u{1F1F8}', group: 'Europa' },
  { code: 'BA', name: 'Bośnia i Hercegowina', flag: '\u{1F1E7}\u{1F1E6}', group: 'Europa' },
  { code: 'ME', name: 'Czarnogóra', flag: '\u{1F1F2}\u{1F1EA}', group: 'Europa' },
  { code: 'MK', name: 'Macedonia Północna', flag: '\u{1F1F2}\u{1F1F0}', group: 'Europa' },
  { code: 'AL', name: 'Albania', flag: '\u{1F1E6}\u{1F1F1}', group: 'Europa' },
  { code: 'XK', name: 'Kosowo', flag: '\u{1F1FD}\u{1F1F0}', group: 'Europa' },
  { code: 'MD', name: 'Mołdawia', flag: '\u{1F1F2}\u{1F1E9}', group: 'Europa' },
  { code: 'CY', name: 'Cypr', flag: '\u{1F1E8}\u{1F1FE}', group: 'Europa' },
  { code: 'MT', name: 'Malta', flag: '\u{1F1F2}\u{1F1F9}', group: 'Europa' },
  { code: 'LU', name: 'Luksemburg', flag: '\u{1F1F1}\u{1F1FA}', group: 'Europa' },
  { code: 'IS', name: 'Islandia', flag: '\u{1F1EE}\u{1F1F8}', group: 'Europa' },
  { code: 'GE', name: 'Gruzja', flag: '\u{1F1EC}\u{1F1EA}', group: 'Europa' },
  { code: 'AM', name: 'Armenia', flag: '\u{1F1E6}\u{1F1F2}', group: 'Europa' },
  { code: 'AZ', name: 'Azerbejdżan', flag: '\u{1F1E6}\u{1F1FF}', group: 'Europa' },
  // Azja
  { code: 'CN', name: 'Chiny', flag: '\u{1F1E8}\u{1F1F3}', group: 'Azja' },
  { code: 'JP', name: 'Japonia', flag: '\u{1F1EF}\u{1F1F5}', group: 'Azja' },
  { code: 'KR', name: 'Korea Południowa', flag: '\u{1F1F0}\u{1F1F7}', group: 'Azja' },
  { code: 'IN', name: 'Indie', flag: '\u{1F1EE}\u{1F1F3}', group: 'Azja' },
  { code: 'TW', name: 'Tajwan', flag: '\u{1F1F9}\u{1F1FC}', group: 'Azja' },
  { code: 'VN', name: 'Wietnam', flag: '\u{1F1FB}\u{1F1F3}', group: 'Azja' },
  { code: 'TH', name: 'Tajlandia', flag: '\u{1F1F9}\u{1F1ED}', group: 'Azja' },
  { code: 'MY', name: 'Malezja', flag: '\u{1F1F2}\u{1F1FE}', group: 'Azja' },
  { code: 'ID', name: 'Indonezja', flag: '\u{1F1EE}\u{1F1E9}', group: 'Azja' },
  { code: 'TR', name: 'Turcja', flag: '\u{1F1F9}\u{1F1F7}', group: 'Azja' },
  { code: 'PH', name: 'Filipiny', flag: '\u{1F1F5}\u{1F1ED}', group: 'Azja' },
  { code: 'SG', name: 'Singapur', flag: '\u{1F1F8}\u{1F1EC}', group: 'Azja' },
  { code: 'BD', name: 'Bangladesz', flag: '\u{1F1E7}\u{1F1E9}', group: 'Azja' },
  { code: 'PK', name: 'Pakistan', flag: '\u{1F1F5}\u{1F1F0}', group: 'Azja' },
  { code: 'LK', name: 'Sri Lanka', flag: '\u{1F1F1}\u{1F1F0}', group: 'Azja' },
  { code: 'KH', name: 'Kambodża', flag: '\u{1F1F0}\u{1F1ED}', group: 'Azja' },
  { code: 'NP', name: 'Nepal', flag: '\u{1F1F3}\u{1F1F5}', group: 'Azja' },
  { code: 'MN', name: 'Mongolia', flag: '\u{1F1F2}\u{1F1F3}', group: 'Azja' },
  { code: 'KZ', name: 'Kazachstan', flag: '\u{1F1F0}\u{1F1FF}', group: 'Azja' },
  { code: 'UZ', name: 'Uzbekistan', flag: '\u{1F1FA}\u{1F1FF}', group: 'Azja' },
  { code: 'AE', name: 'Zjednoczone Emiraty Arabskie', flag: '\u{1F1E6}\u{1F1EA}', group: 'Azja' },
  { code: 'SA', name: 'Arabia Saudyjska', flag: '\u{1F1F8}\u{1F1E6}', group: 'Azja' },
  { code: 'IL', name: 'Izrael', flag: '\u{1F1EE}\u{1F1F1}', group: 'Azja' },
  { code: 'JO', name: 'Jordania', flag: '\u{1F1EF}\u{1F1F4}', group: 'Azja' },
  { code: 'LB', name: 'Liban', flag: '\u{1F1F1}\u{1F1E7}', group: 'Azja' },
  { code: 'OM', name: 'Oman', flag: '\u{1F1F4}\u{1F1F2}', group: 'Azja' },
  { code: 'QA', name: 'Katar', flag: '\u{1F1F6}\u{1F1E6}', group: 'Azja' },
  { code: 'BH', name: 'Bahrajn', flag: '\u{1F1E7}\u{1F1ED}', group: 'Azja' },
  { code: 'KW', name: 'Kuwejt', flag: '\u{1F1F0}\u{1F1FC}', group: 'Azja' },
  { code: 'IQ', name: 'Irak', flag: '\u{1F1EE}\u{1F1F6}', group: 'Azja' },
  { code: 'LA', name: 'Laos', flag: '\u{1F1F1}\u{1F1E6}', group: 'Azja' },
  // Afryka
  { code: 'ZA', name: 'RPA', flag: '\u{1F1FF}\u{1F1E6}', group: 'Afryka' },
  { code: 'EG', name: 'Egipt', flag: '\u{1F1EA}\u{1F1EC}', group: 'Afryka' },
  { code: 'MA', name: 'Maroko', flag: '\u{1F1F2}\u{1F1E6}', group: 'Afryka' },
  { code: 'NG', name: 'Nigeria', flag: '\u{1F1F3}\u{1F1EC}', group: 'Afryka' },
  { code: 'KE', name: 'Kenia', flag: '\u{1F1F0}\u{1F1EA}', group: 'Afryka' },
  { code: 'TN', name: 'Tunezja', flag: '\u{1F1F9}\u{1F1F3}', group: 'Afryka' },
  { code: 'GH', name: 'Ghana', flag: '\u{1F1EC}\u{1F1ED}', group: 'Afryka' },
  { code: 'ET', name: 'Etiopia', flag: '\u{1F1EA}\u{1F1F9}', group: 'Afryka' },
  { code: 'TZ', name: 'Tanzania', flag: '\u{1F1F9}\u{1F1FF}', group: 'Afryka' },
  { code: 'DZ', name: 'Algieria', flag: '\u{1F1E9}\u{1F1FF}', group: 'Afryka' },
  { code: 'SN', name: 'Senegal', flag: '\u{1F1F8}\u{1F1F3}', group: 'Afryka' },
  { code: 'CI', name: 'Wybrzeże Kości Słoniowej', flag: '\u{1F1E8}\u{1F1EE}', group: 'Afryka' },
  { code: 'CM', name: 'Kamerun', flag: '\u{1F1E8}\u{1F1F2}', group: 'Afryka' },
  { code: 'UG', name: 'Uganda', flag: '\u{1F1FA}\u{1F1EC}', group: 'Afryka' },
  { code: 'MZ', name: 'Mozambik', flag: '\u{1F1F2}\u{1F1FF}', group: 'Afryka' },
  { code: 'AO', name: 'Angola', flag: '\u{1F1E6}\u{1F1F4}', group: 'Afryka' },
  { code: 'CD', name: 'DR Konga', flag: '\u{1F1E8}\u{1F1E9}', group: 'Afryka' },
  { code: 'MG', name: 'Madagaskar', flag: '\u{1F1F2}\u{1F1EC}', group: 'Afryka' },
  { code: 'RW', name: 'Rwanda', flag: '\u{1F1F7}\u{1F1FC}', group: 'Afryka' },
  { code: 'ZM', name: 'Zambia', flag: '\u{1F1FF}\u{1F1F2}', group: 'Afryka' },
  { code: 'ZW', name: 'Zimbabwe', flag: '\u{1F1FF}\u{1F1FC}', group: 'Afryka' },
  { code: 'BW', name: 'Botswana', flag: '\u{1F1E7}\u{1F1FC}', group: 'Afryka' },
  { code: 'NA', name: 'Namibia', flag: '\u{1F1F3}\u{1F1E6}', group: 'Afryka' },
  { code: 'MU', name: 'Mauritius', flag: '\u{1F1F2}\u{1F1FA}', group: 'Afryka' },
  { code: 'LY', name: 'Libia', flag: '\u{1F1F1}\u{1F1FE}', group: 'Afryka' },
  { code: 'ML', name: 'Mali', flag: '\u{1F1F2}\u{1F1F1}', group: 'Afryka' },
  { code: 'BF', name: 'Burkina Faso', flag: '\u{1F1E7}\u{1F1EB}', group: 'Afryka' },
  { code: 'NE', name: 'Niger', flag: '\u{1F1F3}\u{1F1EA}', group: 'Afryka' },
  { code: 'MW', name: 'Malawi', flag: '\u{1F1F2}\u{1F1FC}', group: 'Afryka' },
  // Ameryki
  { code: 'US', name: 'USA', flag: '\u{1F1FA}\u{1F1F8}', group: 'Ameryki' },
  { code: 'CA', name: 'Kanada', flag: '\u{1F1E8}\u{1F1E6}', group: 'Ameryki' },
  { code: 'MX', name: 'Meksyk', flag: '\u{1F1F2}\u{1F1FD}', group: 'Ameryki' },
  { code: 'BR', name: 'Brazylia', flag: '\u{1F1E7}\u{1F1F7}', group: 'Ameryki' },
  { code: 'AR', name: 'Argentyna', flag: '\u{1F1E6}\u{1F1F7}', group: 'Ameryki' },
  { code: 'CL', name: 'Chile', flag: '\u{1F1E8}\u{1F1F1}', group: 'Ameryki' },
  { code: 'CO', name: 'Kolumbia', flag: '\u{1F1E8}\u{1F1F4}', group: 'Ameryki' },
  { code: 'PE', name: 'Peru', flag: '\u{1F1F5}\u{1F1EA}', group: 'Ameryki' },
  { code: 'EC', name: 'Ekwador', flag: '\u{1F1EA}\u{1F1E8}', group: 'Ameryki' },
  { code: 'UY', name: 'Urugwaj', flag: '\u{1F1FA}\u{1F1FE}', group: 'Ameryki' },
  { code: 'PY', name: 'Paragwaj', flag: '\u{1F1F5}\u{1F1FE}', group: 'Ameryki' },
  { code: 'BO', name: 'Boliwia', flag: '\u{1F1E7}\u{1F1F4}', group: 'Ameryki' },
  { code: 'CR', name: 'Kostaryka', flag: '\u{1F1E8}\u{1F1F7}', group: 'Ameryki' },
  { code: 'PA', name: 'Panama', flag: '\u{1F1F5}\u{1F1E6}', group: 'Ameryki' },
  { code: 'DO', name: 'Dominikana', flag: '\u{1F1E9}\u{1F1F4}', group: 'Ameryki' },
  { code: 'GT', name: 'Gwatemala', flag: '\u{1F1EC}\u{1F1F9}', group: 'Ameryki' },
  { code: 'HN', name: 'Honduras', flag: '\u{1F1ED}\u{1F1F3}', group: 'Ameryki' },
  { code: 'SV', name: 'Salwador', flag: '\u{1F1F8}\u{1F1FB}', group: 'Ameryki' },
  { code: 'NI', name: 'Nikaragua', flag: '\u{1F1F3}\u{1F1EE}', group: 'Ameryki' },
  { code: 'JM', name: 'Jamajka', flag: '\u{1F1EF}\u{1F1F2}', group: 'Ameryki' },
  { code: 'TT', name: 'Trynidad i Tobago', flag: '\u{1F1F9}\u{1F1F9}', group: 'Ameryki' },
  // Oceania
  { code: 'AU', name: 'Australia', flag: '\u{1F1E6}\u{1F1FA}', group: 'Oceania' },
  { code: 'NZ', name: 'Nowa Zelandia', flag: '\u{1F1F3}\u{1F1FF}', group: 'Oceania' },
  { code: 'FJ', name: 'Fidżi', flag: '\u{1F1EB}\u{1F1EF}', group: 'Oceania' },
  { code: 'PG', name: 'Papua Nowa Gwinea', flag: '\u{1F1F5}\u{1F1EC}', group: 'Oceania' },
];

export const COUNTRIES_EN: CountryOption[] = [
  // Europe
  { code: 'AL', name: 'Albania', flag: '\u{1F1E6}\u{1F1F1}', group: 'Europe' },
  { code: 'AM', name: 'Armenia', flag: '\u{1F1E6}\u{1F1F2}', group: 'Europe' },
  { code: 'AT', name: 'Austria', flag: '\u{1F1E6}\u{1F1F9}', group: 'Europe' },
  { code: 'AZ', name: 'Azerbaijan', flag: '\u{1F1E6}\u{1F1FF}', group: 'Europe' },
  { code: 'BE', name: 'Belgium', flag: '\u{1F1E7}\u{1F1EA}', group: 'Europe' },
  { code: 'BA', name: 'Bosnia and Herzegovina', flag: '\u{1F1E7}\u{1F1E6}', group: 'Europe' },
  { code: 'BG', name: 'Bulgaria', flag: '\u{1F1E7}\u{1F1EC}', group: 'Europe' },
  { code: 'HR', name: 'Croatia', flag: '\u{1F1ED}\u{1F1F7}', group: 'Europe' },
  { code: 'CY', name: 'Cyprus', flag: '\u{1F1E8}\u{1F1FE}', group: 'Europe' },
  { code: 'CZ', name: 'Czechia', flag: '\u{1F1E8}\u{1F1FF}', group: 'Europe' },
  { code: 'DK', name: 'Denmark', flag: '\u{1F1E9}\u{1F1F0}', group: 'Europe' },
  { code: 'EE', name: 'Estonia', flag: '\u{1F1EA}\u{1F1EA}', group: 'Europe' },
  { code: 'FI', name: 'Finland', flag: '\u{1F1EB}\u{1F1EE}', group: 'Europe' },
  { code: 'FR', name: 'France', flag: '\u{1F1EB}\u{1F1F7}', group: 'Europe' },
  { code: 'GE', name: 'Georgia', flag: '\u{1F1EC}\u{1F1EA}', group: 'Europe' },
  { code: 'DE', name: 'Germany', flag: '\u{1F1E9}\u{1F1EA}', group: 'Europe' },
  { code: 'GR', name: 'Greece', flag: '\u{1F1EC}\u{1F1F7}', group: 'Europe' },
  { code: 'HU', name: 'Hungary', flag: '\u{1F1ED}\u{1F1FA}', group: 'Europe' },
  { code: 'IS', name: 'Iceland', flag: '\u{1F1EE}\u{1F1F8}', group: 'Europe' },
  { code: 'IE', name: 'Ireland', flag: '\u{1F1EE}\u{1F1EA}', group: 'Europe' },
  { code: 'IT', name: 'Italy', flag: '\u{1F1EE}\u{1F1F9}', group: 'Europe' },
  { code: 'XK', name: 'Kosovo', flag: '\u{1F1FD}\u{1F1F0}', group: 'Europe' },
  { code: 'LV', name: 'Latvia', flag: '\u{1F1F1}\u{1F1FB}', group: 'Europe' },
  { code: 'LT', name: 'Lithuania', flag: '\u{1F1F1}\u{1F1F9}', group: 'Europe' },
  { code: 'LU', name: 'Luxembourg', flag: '\u{1F1F1}\u{1F1FA}', group: 'Europe' },
  { code: 'MT', name: 'Malta', flag: '\u{1F1F2}\u{1F1F9}', group: 'Europe' },
  { code: 'MD', name: 'Moldova', flag: '\u{1F1F2}\u{1F1E9}', group: 'Europe' },
  { code: 'ME', name: 'Montenegro', flag: '\u{1F1F2}\u{1F1EA}', group: 'Europe' },
  { code: 'NL', name: 'Netherlands', flag: '\u{1F1F3}\u{1F1F1}', group: 'Europe' },
  { code: 'MK', name: 'North Macedonia', flag: '\u{1F1F2}\u{1F1F0}', group: 'Europe' },
  { code: 'NO', name: 'Norway', flag: '\u{1F1F3}\u{1F1F4}', group: 'Europe' },
  { code: 'PL', name: 'Poland', flag: '\u{1F1F5}\u{1F1F1}', group: 'Europe' },
  { code: 'PT', name: 'Portugal', flag: '\u{1F1F5}\u{1F1F9}', group: 'Europe' },
  { code: 'RO', name: 'Romania', flag: '\u{1F1F7}\u{1F1F4}', group: 'Europe' },
  { code: 'RS', name: 'Serbia', flag: '\u{1F1F7}\u{1F1F8}', group: 'Europe' },
  { code: 'SK', name: 'Slovakia', flag: '\u{1F1F8}\u{1F1F0}', group: 'Europe' },
  { code: 'SI', name: 'Slovenia', flag: '\u{1F1F8}\u{1F1EE}', group: 'Europe' },
  { code: 'ES', name: 'Spain', flag: '\u{1F1EA}\u{1F1F8}', group: 'Europe' },
  { code: 'SE', name: 'Sweden', flag: '\u{1F1F8}\u{1F1EA}', group: 'Europe' },
  { code: 'CH', name: 'Switzerland', flag: '\u{1F1E8}\u{1F1ED}', group: 'Europe' },
  { code: 'UA', name: 'Ukraine', flag: '\u{1F1FA}\u{1F1E6}', group: 'Europe' },
  { code: 'GB', name: 'United Kingdom', flag: '\u{1F1EC}\u{1F1E7}', group: 'Europe' },
  // Asia
  { code: 'BH', name: 'Bahrain', flag: '\u{1F1E7}\u{1F1ED}', group: 'Asia' },
  { code: 'BD', name: 'Bangladesh', flag: '\u{1F1E7}\u{1F1E9}', group: 'Asia' },
  { code: 'KH', name: 'Cambodia', flag: '\u{1F1F0}\u{1F1ED}', group: 'Asia' },
  { code: 'CN', name: 'China', flag: '\u{1F1E8}\u{1F1F3}', group: 'Asia' },
  { code: 'IN', name: 'India', flag: '\u{1F1EE}\u{1F1F3}', group: 'Asia' },
  { code: 'ID', name: 'Indonesia', flag: '\u{1F1EE}\u{1F1E9}', group: 'Asia' },
  { code: 'IQ', name: 'Iraq', flag: '\u{1F1EE}\u{1F1F6}', group: 'Asia' },
  { code: 'IL', name: 'Israel', flag: '\u{1F1EE}\u{1F1F1}', group: 'Asia' },
  { code: 'JP', name: 'Japan', flag: '\u{1F1EF}\u{1F1F5}', group: 'Asia' },
  { code: 'JO', name: 'Jordan', flag: '\u{1F1EF}\u{1F1F4}', group: 'Asia' },
  { code: 'KZ', name: 'Kazakhstan', flag: '\u{1F1F0}\u{1F1FF}', group: 'Asia' },
  { code: 'KW', name: 'Kuwait', flag: '\u{1F1F0}\u{1F1FC}', group: 'Asia' },
  { code: 'LA', name: 'Laos', flag: '\u{1F1F1}\u{1F1E6}', group: 'Asia' },
  { code: 'LB', name: 'Lebanon', flag: '\u{1F1F1}\u{1F1E7}', group: 'Asia' },
  { code: 'MY', name: 'Malaysia', flag: '\u{1F1F2}\u{1F1FE}', group: 'Asia' },
  { code: 'MN', name: 'Mongolia', flag: '\u{1F1F2}\u{1F1F3}', group: 'Asia' },
  { code: 'NP', name: 'Nepal', flag: '\u{1F1F3}\u{1F1F5}', group: 'Asia' },
  { code: 'OM', name: 'Oman', flag: '\u{1F1F4}\u{1F1F2}', group: 'Asia' },
  { code: 'PK', name: 'Pakistan', flag: '\u{1F1F5}\u{1F1F0}', group: 'Asia' },
  { code: 'PH', name: 'Philippines', flag: '\u{1F1F5}\u{1F1ED}', group: 'Asia' },
  { code: 'QA', name: 'Qatar', flag: '\u{1F1F6}\u{1F1E6}', group: 'Asia' },
  { code: 'SA', name: 'Saudi Arabia', flag: '\u{1F1F8}\u{1F1E6}', group: 'Asia' },
  { code: 'SG', name: 'Singapore', flag: '\u{1F1F8}\u{1F1EC}', group: 'Asia' },
  { code: 'KR', name: 'South Korea', flag: '\u{1F1F0}\u{1F1F7}', group: 'Asia' },
  { code: 'LK', name: 'Sri Lanka', flag: '\u{1F1F1}\u{1F1F0}', group: 'Asia' },
  { code: 'TW', name: 'Taiwan', flag: '\u{1F1F9}\u{1F1FC}', group: 'Asia' },
  { code: 'TH', name: 'Thailand', flag: '\u{1F1F9}\u{1F1ED}', group: 'Asia' },
  { code: 'TR', name: 'Turkey', flag: '\u{1F1F9}\u{1F1F7}', group: 'Asia' },
  { code: 'AE', name: 'United Arab Emirates', flag: '\u{1F1E6}\u{1F1EA}', group: 'Asia' },
  { code: 'UZ', name: 'Uzbekistan', flag: '\u{1F1FA}\u{1F1FF}', group: 'Asia' },
  { code: 'VN', name: 'Vietnam', flag: '\u{1F1FB}\u{1F1F3}', group: 'Asia' },
  // Africa
  { code: 'DZ', name: 'Algeria', flag: '\u{1F1E9}\u{1F1FF}', group: 'Africa' },
  { code: 'AO', name: 'Angola', flag: '\u{1F1E6}\u{1F1F4}', group: 'Africa' },
  { code: 'BW', name: 'Botswana', flag: '\u{1F1E7}\u{1F1FC}', group: 'Africa' },
  { code: 'BF', name: 'Burkina Faso', flag: '\u{1F1E7}\u{1F1EB}', group: 'Africa' },
  { code: 'CM', name: 'Cameroon', flag: '\u{1F1E8}\u{1F1F2}', group: 'Africa' },
  { code: 'CD', name: 'DR Congo', flag: '\u{1F1E8}\u{1F1E9}', group: 'Africa' },
  { code: 'EG', name: 'Egypt', flag: '\u{1F1EA}\u{1F1EC}', group: 'Africa' },
  { code: 'ET', name: 'Ethiopia', flag: '\u{1F1EA}\u{1F1F9}', group: 'Africa' },
  { code: 'GH', name: 'Ghana', flag: '\u{1F1EC}\u{1F1ED}', group: 'Africa' },
  { code: 'CI', name: 'Ivory Coast', flag: '\u{1F1E8}\u{1F1EE}', group: 'Africa' },
  { code: 'KE', name: 'Kenya', flag: '\u{1F1F0}\u{1F1EA}', group: 'Africa' },
  { code: 'LY', name: 'Libya', flag: '\u{1F1F1}\u{1F1FE}', group: 'Africa' },
  { code: 'MG', name: 'Madagascar', flag: '\u{1F1F2}\u{1F1EC}', group: 'Africa' },
  { code: 'MW', name: 'Malawi', flag: '\u{1F1F2}\u{1F1FC}', group: 'Africa' },
  { code: 'ML', name: 'Mali', flag: '\u{1F1F2}\u{1F1F1}', group: 'Africa' },
  { code: 'MU', name: 'Mauritius', flag: '\u{1F1F2}\u{1F1FA}', group: 'Africa' },
  { code: 'MA', name: 'Morocco', flag: '\u{1F1F2}\u{1F1E6}', group: 'Africa' },
  { code: 'MZ', name: 'Mozambique', flag: '\u{1F1F2}\u{1F1FF}', group: 'Africa' },
  { code: 'NA', name: 'Namibia', flag: '\u{1F1F3}\u{1F1E6}', group: 'Africa' },
  { code: 'NE', name: 'Niger', flag: '\u{1F1F3}\u{1F1EA}', group: 'Africa' },
  { code: 'NG', name: 'Nigeria', flag: '\u{1F1F3}\u{1F1EC}', group: 'Africa' },
  { code: 'RW', name: 'Rwanda', flag: '\u{1F1F7}\u{1F1FC}', group: 'Africa' },
  { code: 'SN', name: 'Senegal', flag: '\u{1F1F8}\u{1F1F3}', group: 'Africa' },
  { code: 'ZA', name: 'South Africa', flag: '\u{1F1FF}\u{1F1E6}', group: 'Africa' },
  { code: 'TZ', name: 'Tanzania', flag: '\u{1F1F9}\u{1F1FF}', group: 'Africa' },
  { code: 'TN', name: 'Tunisia', flag: '\u{1F1F9}\u{1F1F3}', group: 'Africa' },
  { code: 'UG', name: 'Uganda', flag: '\u{1F1FA}\u{1F1EC}', group: 'Africa' },
  { code: 'ZM', name: 'Zambia', flag: '\u{1F1FF}\u{1F1F2}', group: 'Africa' },
  { code: 'ZW', name: 'Zimbabwe', flag: '\u{1F1FF}\u{1F1FC}', group: 'Africa' },
  // Americas
  { code: 'AR', name: 'Argentina', flag: '\u{1F1E6}\u{1F1F7}', group: 'Americas' },
  { code: 'BO', name: 'Bolivia', flag: '\u{1F1E7}\u{1F1F4}', group: 'Americas' },
  { code: 'BR', name: 'Brazil', flag: '\u{1F1E7}\u{1F1F7}', group: 'Americas' },
  { code: 'CA', name: 'Canada', flag: '\u{1F1E8}\u{1F1E6}', group: 'Americas' },
  { code: 'CL', name: 'Chile', flag: '\u{1F1E8}\u{1F1F1}', group: 'Americas' },
  { code: 'CO', name: 'Colombia', flag: '\u{1F1E8}\u{1F1F4}', group: 'Americas' },
  { code: 'CR', name: 'Costa Rica', flag: '\u{1F1E8}\u{1F1F7}', group: 'Americas' },
  { code: 'DO', name: 'Dominican Republic', flag: '\u{1F1E9}\u{1F1F4}', group: 'Americas' },
  { code: 'EC', name: 'Ecuador', flag: '\u{1F1EA}\u{1F1E8}', group: 'Americas' },
  { code: 'SV', name: 'El Salvador', flag: '\u{1F1F8}\u{1F1FB}', group: 'Americas' },
  { code: 'GT', name: 'Guatemala', flag: '\u{1F1EC}\u{1F1F9}', group: 'Americas' },
  { code: 'HN', name: 'Honduras', flag: '\u{1F1ED}\u{1F1F3}', group: 'Americas' },
  { code: 'JM', name: 'Jamaica', flag: '\u{1F1EF}\u{1F1F2}', group: 'Americas' },
  { code: 'MX', name: 'Mexico', flag: '\u{1F1F2}\u{1F1FD}', group: 'Americas' },
  { code: 'NI', name: 'Nicaragua', flag: '\u{1F1F3}\u{1F1EE}', group: 'Americas' },
  { code: 'PA', name: 'Panama', flag: '\u{1F1F5}\u{1F1E6}', group: 'Americas' },
  { code: 'PY', name: 'Paraguay', flag: '\u{1F1F5}\u{1F1FE}', group: 'Americas' },
  { code: 'PE', name: 'Peru', flag: '\u{1F1F5}\u{1F1EA}', group: 'Americas' },
  { code: 'TT', name: 'Trinidad and Tobago', flag: '\u{1F1F9}\u{1F1F9}', group: 'Americas' },
  { code: 'US', name: 'USA', flag: '\u{1F1FA}\u{1F1F8}', group: 'Americas' },
  { code: 'UY', name: 'Uruguay', flag: '\u{1F1FA}\u{1F1FE}', group: 'Americas' },
  // Oceania
  { code: 'AU', name: 'Australia', flag: '\u{1F1E6}\u{1F1FA}', group: 'Oceania' },
  { code: 'FJ', name: 'Fiji', flag: '\u{1F1EB}\u{1F1EF}', group: 'Oceania' },
  { code: 'NZ', name: 'New Zealand', flag: '\u{1F1F3}\u{1F1FF}', group: 'Oceania' },
  { code: 'PG', name: 'Papua New Guinea', flag: '\u{1F1F5}\u{1F1EC}', group: 'Oceania' },
];

export const AVAILABLE_COUNTRIES = isEN ? COUNTRIES_EN : COUNTRIES_PL;
