import { LegalLayout } from "@/components/layout/LegalLayout"

export function TermsPage() {
  return (
    <LegalLayout title="Terms of Service" lastUpdated="February 18, 2026">
      <h2>§1. General Provisions</h2>
      <ol>
        <li>These Terms of Service govern the use of the Procurea online platform, available at app.procurea.io (hereinafter: the "Platform").</li>
        <li>The owner and operator of the Platform is <strong>Procurea sp. z o.o.</strong>, registered at ul. Pomorska 3/1, 85-050 Bydgoszcz, Poland, entered in the National Court Register (hereinafter: the "Provider").</li>
        <li>By using the Platform, you agree to these Terms of Service.</li>
      </ol>

      <h2>§2. Definitions</h2>
      <ol>
        <li><strong>Platform</strong> — the Procurea web application that enables automated supplier discovery, analysis, and verification using AI agents.</li>
        <li><strong>User</strong> — a natural person, legal entity, or organizational unit without legal personality that uses the Platform.</li>
        <li><strong>Account</strong> — an individual User account created on the Platform after registration.</li>
        <li><strong>Credit</strong> — a billing unit entitling the User to run one complete AI sourcing process on the Platform.</li>
        <li><strong>Sourcing Process</strong> — a multi-stage supplier discovery process performed by the Platform's AI agents, including strategy generation, scanning, analysis, data enrichment, and results generation.</li>
        <li><strong>Supplier Portal</strong> — a Platform feature that allows suppliers to submit quotes without registration, via a unique link.</li>
      </ol>

      <h2>§3. Registration and Account</h2>
      <ol>
        <li>Registration on the Platform is performed via OAuth 2.0 authentication (Google or Microsoft) and phone number verification.</li>
        <li>The User is required to provide truthful and current information during registration, including organization and position details.</li>
        <li>Each User may have one Account on the Platform.</li>
        <li>The User is responsible for maintaining the confidentiality of their Account access credentials.</li>
      </ol>

      <h2>§4. Scope of Services</h2>
      <ol>
        <li>The Platform enables Users to:
          <ul>
            <li>create sourcing campaigns using AI agents,</li>
            <li>automatically discover suppliers across multiple languages and regions,</li>
            <li>analyze and score suppliers based on available data,</li>
            <li>automatically enrich supplier contact information,</li>
            <li>send requests for quotation (RFQ) to suppliers,</li>
            <li>use the supplier portal to collect quotes,</li>
            <li>automate email sequences and follow-ups,</li>
            <li>export results and data.</li>
          </ul>
        </li>
        <li>The Provider reserves the right to modify the scope of the Platform's functionality.</li>
      </ol>

      <h2>§5. Billing Model</h2>
      <ol>
        <li>The Platform operates on a pay-as-you-go model. One Credit entitles the User to run one AI sourcing process.</li>
        <li>Each new User receives 3 (three) free Credits upon registration.</li>
        <li>Credits can be purchased individually or in packs. Current pricing is available at procurea.io in the "Pricing" section.</li>
        <li>Purchased Credits are non-refundable, unless a sourcing process was not initiated due to a technical issue on the Provider's side.</li>
        <li>The Provider may offer time-limited promotional pricing. Promotion terms are published on the website.</li>
      </ol>

      <h2>§6. Liability</h2>
      <ol>
        <li>The Provider makes every effort to ensure that results generated by AI agents are accurate and up-to-date. Results are informational in nature and do not constitute business recommendations.</li>
        <li>The Provider is not liable for:
          <ul>
            <li>business decisions made by the User based on Platform results,</li>
            <li>the accuracy and currency of publicly available internet data used by AI agents,</li>
            <li>Platform outages caused by factors beyond the Provider's control.</li>
          </ul>
        </li>
        <li>The User agrees to use the Platform in accordance with applicable law and these Terms of Service.</li>
      </ol>

      <h2>§7. Data Protection</h2>
      <ol>
        <li>The data controller for User personal data is Procurea sp. z o.o., registered at ul. Pomorska 3/1, 85-050 Bydgoszcz, Poland.</li>
        <li>Detailed information about personal data processing can be found in the <a href="/privacy">Privacy Policy</a> and <a href="/gdpr">GDPR Information Notice</a>.</li>
      </ol>

      <h2>§8. Complaints</h2>
      <ol>
        <li>Complaints regarding the Platform's operation can be submitted electronically to: <strong>hello@procurea.io</strong>.</li>
        <li>The Provider will process complaints within 14 business days of receipt.</li>
        <li>A complaint should include: User details, a description of the issue, and the expected resolution.</li>
      </ol>

      <h2>§9. Termination</h2>
      <ol>
        <li>The User may delete their Account at any time by contacting the Provider at hello@procurea.io.</li>
        <li>The Provider may suspend or delete a User's Account in case of a breach of these Terms of Service.</li>
        <li>Account deletion does not result in a refund of unused Credits, except as described in §5(4).</li>
      </ol>

      <h2>§10. Final Provisions</h2>
      <ol>
        <li>The Provider reserves the right to amend these Terms of Service. Users will be notified of changes electronically with 14 days' advance notice.</li>
        <li>Matters not regulated by these Terms of Service shall be governed by Polish law.</li>
        <li>Any disputes arising from the use of the Platform shall be resolved by the court having jurisdiction over the Provider's registered office.</li>
        <li>These Terms of Service are effective as of February 18, 2026.</li>
      </ol>

      <h2>Contact Information</h2>
      <p>
        <strong>Procurea sp. z o.o.</strong><br />
        ul. Pomorska 3/1, 85-050 Bydgoszcz, Poland<br />
        Email: hello@procurea.io
      </p>
    </LegalLayout>
  )
}
